ALTER TABLE posts ADD (
    latitude NUMBER(15, 10),
    longitude NUMBER(15, 10)
);

CREATE TABLE post_locations (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id NUMBER NOT NULL,
  location_name VARCHAR2(120) NOT NULL,
  latitude NUMBER(15, 10) NOT NULL,
  longitude NUMBER(15, 10) NOT NULL,
  sort_order NUMBER(10) DEFAULT 0 NOT NULL,
  CONSTRAINT fk_post_locations_post
    FOREIGN KEY (post_id)
    REFERENCES posts(id)
    ON DELETE CASCADE
);
